"use strict";
(function(root,factory){var api=factory();if(typeof module==='object'&&module.exports)module.exports=api;root.DrawForgeGeometry3D=api})(typeof globalThis!=='undefined'?globalThis:this,function(){
 function signedArea(p){var a=0;for(var i=0;i<p.length;i++){var j=(i+1)%p.length;a+=p[i].x*p[j].y-p[j].x*p[i].y}return a/2}function area(p){return Math.abs(signedArea(p))}function centroid(p){var x=0,y=0;for(var i=0;i<p.length;i++){x+=p[i].x;y+=p[i].y}return{x:x/p.length,y:y/p.length}}
 function pointInPoly(pt,poly){var inside=false;for(var i=0,j=poly.length-1;i<poly.length;j=i++){var a=poly[i],b=poly[j];if(((a.y>pt.y)!==(b.y>pt.y))&&(pt.x<(b.x-a.x)*(pt.y-a.y)/(b.y-a.y+1e-12)+a.x))inside=!inside}return inside}
 function polygon(el,n){var out=[],i;if(el.type==='rect')return[{x:el.x,y:el.y},{x:el.x+el.w,y:el.y},{x:el.x+el.w,y:el.y+el.h},{x:el.x,y:el.y+el.h}];if(el.type==='circle'){n=n||64;for(i=0;i<n;i++){var a=i/n*Math.PI*2;out.push({x:el.cx+Math.cos(a)*el.r,y:el.cy+Math.sin(a)*el.r})}return out}if(el.points&&el.points.length>2)return el.points.map(function(p){return{x:p.x,y:p.y}});return null}
 function closed(e){return e&&(e.type==='rect'||e.type==='circle'||e.type==='polygon'||(e.type==='polyline'&&e.closed))}function orient(p,ccw){return(signedArea(p)>0)===ccw?p.slice():p.slice().reverse()}function flip(p){return p.map(function(q){return{x:q.x,y:-q.y}})}
 function edgeFeature(poly,el){var amount=Math.max(0,+el.edgeSize||0),mode=el.edgeFeature;if(!amount||!mode||poly.length<3)return poly;var out=[];for(var i=0;i<poly.length;i++){var prev=poly[(i+poly.length-1)%poly.length],cur=poly[i],next=poly[(i+1)%poly.length],a=Math.hypot(prev.x-cur.x,prev.y-cur.y),b=Math.hypot(next.x-cur.x,next.y-cur.y),cut=Math.min(amount,a*.45,b*.45);if(mode==='chamfer'){out.push({x:cur.x+(prev.x-cur.x)*cut/a,y:cur.y+(prev.y-cur.y)*cut/a});out.push({x:cur.x+(next.x-cur.x)*cut/b,y:cur.y+(next.y-cur.y)*cut/b})}else{var steps=Math.max(3,Math.min(12,Math.ceil(cut/2))),p1={x:cur.x+(prev.x-cur.x)*cut/a,y:cur.y+(prev.y-cur.y)*cut/a},p2={x:cur.x+(next.x-cur.x)*cut/b,y:cur.y+(next.y-cur.y)*cut/b};for(var s=0;s<=steps;s++){var u=s/steps*Math.PI/2;out.push({x:cur.x+(p1.x-cur.x)*Math.cos(u)+(p2.x-cur.x)*Math.sin(u),y:cur.y+(p1.y-cur.y)*Math.cos(u)+(p2.y-cur.y)*Math.sin(u)})}}}return out}
 function feature(el){var poly=polygon(el,el.circleSegments);return poly?edgeFeature(poly,el):null}
 function buildParts(elements,globalDepth,opt){opt=opt||{};globalDepth=Math.max(1,+globalDepth||40);var items=[];(elements||[]).filter(closed).forEach(function(el){var poly=feature(el);if(poly)items.push({el:el,poly:poly,area:area(poly),center:centroid(poly),host:null,role:null})});for(var i=0;i<items.length;i++)for(var k=0;k<items.length;k++){if(i===k||items[k].area<=items[i].area||!pointInPoly(items[i].center,items[k].poly))continue;if(!items[i].host||items[k].area<items[i].host.area)items[i].host=items[k]}items.forEach(function(it){var r=it.el.role;if(!r||r==='auto')r=(it.el.type==='circle'&&it.host)?'hole':'body';if((r==='hole'||r==='boss'||r==='cutout'||r==='groove')&&!it.host)r='body';it.role=r});var parts=[],map={};items.forEach(function(it){if(it.role!=='body')return;var d=Math.max(1,+it.el.depth||globalDepth),part={outer:orient(flip(it.poly),true),holes:[],cuts:[],z0:0,z1:d,source:it,src:it};parts.push(part);if(it.el.id)map[it.el.id]=part});function hostPart(it){var h=it.host,g=0;while(h&&g++<20){if(h.el.id&&map[h.el.id])return map[h.el.id];h=h.host}return null}items.forEach(function(it){var hp=hostPart(it);if(!hp)return;var e=it.el;if(it.role==='hole'){var through=e.through!==false,max=hp.z1-hp.z0,depth=Math.min(Math.max(1,+e.depth||max),max);hp.holes.push({ring:orient(flip(it.poly),false),depth:depth,through:through||depth>=max-.001,source:it})}if(it.role==='cutout'||it.role==='groove'){var max2=hp.z1-hp.z0,depth2=Math.min(Math.max(1,+e.depth||max2),max2);hp.cuts.push({ring:orient(flip(it.poly),false),depth:depth2,through:e.through===true||depth2>=max2-.001,source:it})}});items.forEach(function(it){if(it.role!=='boss')return;var hp=hostPart(it),base=hp?hp.z1:globalDepth,height=Math.max(1,+it.el.depth||Math.max(6,globalDepth*.4));parts.push({outer:orient(flip(it.poly),true),holes:[],cuts:[],z0:base,z1:base+height,source:it,src:it})});return parts}
 function ring3(r,z){return r.map(function(p){return[p.x,p.y,z]})}function radius(r){var c=centroid(r),m=0;r.forEach(function(p){m=Math.max(m,Math.hypot(p.x-c.x,p.y-c.y))});return m||1}
 function makeFaces(parts){var faces=[];function walls(r,z0,z1,meta,segs){segs=Math.max(1,segs||1);for(var i=0;i<r.length;i++){var a=r[i],b=r[(i+1)%r.length],dx=b.x-a.x,dy=b.y-a.y,len=Math.hypot(dx,dy)||1;for(var s=0;s<segs;s++){var za=z0+(z1-z0)*s/segs,zb=z0+(z1-z0)*(s+1)/segs;faces.push({rings:[[[a.x,a.y,za],[b.x,b.y,za],[b.x,b.y,zb],[a.x,a.y,zb]]],n:[dy/len,-dx/len,0],hole:meta||null})}}}function caps(p){var through=p.holes.concat(p.cuts).filter(function(h){return h.through}),back=[ring3(p.outer,p.z0)],front=[ring3(p.outer,p.z1)];through.forEach(function(h){back.push(ring3(h.ring,p.z0))});p.holes.concat(p.cuts).forEach(function(h){front.push(ring3(h.ring,p.z1))});faces.push({rings:back,n:[0,0,-1]});faces.push({rings:front,n:[0,0,1]})}
  (parts||[]).forEach(function(p){caps(p);walls(p.outer,p.z0,p.z1,null,1);p.holes.concat(p.cuts).forEach(function(h){var bottom=h.through?p.z0:Math.max(p.z0,p.z1-h.depth),meta={top:ring3(h.ring,p.z1),bot:ring3(h.ring,bottom),through:h.through},segs=Math.max(1,Math.min(28,Math.round((p.z1-bottom)/(radius(h.ring)*.45))));walls(h.ring,bottom,p.z1,meta,segs);if(!h.through&&bottom>p.z0+.001)faces.push({rings:[ring3(h.ring,bottom)],n:[0,0,1],floor:true,hole:meta})})});return faces}
 function bounds(parts){var x1=Infinity,y1=Infinity,z1=Infinity,x2=-Infinity,y2=-Infinity,z2=-Infinity;(parts||[]).forEach(function(p){p.outer.forEach(function(q){x1=Math.min(x1,q.x);x2=Math.max(x2,q.x);y1=Math.min(y1,q.y);y2=Math.max(y2,q.y)});z1=Math.min(z1,p.z0);z2=Math.max(z2,p.z1)});return isFinite(x1)?{x1:x1,y1:y1,z1:z1,x2:x2,y2:y2,z2:z2,w:x2-x1,h:y2-y1,d:z2-z1}:null}
 return{signedArea:signedArea,area:area,centroid:centroid,pointInPoly:pointInPoly,polygon:polygon,edgeFeature:edgeFeature,feature:feature,buildParts:buildParts,makeFaces:makeFaces,bounds:bounds}
});
