"use strict";
(function(root,factory){var api=factory();if(typeof module==='object'&&module.exports)module.exports=api;root.DrawForgeSTL=api})(typeof globalThis!=='undefined'?globalThis:this,function(){
 function n(v){v=Math.round(v*1e5)/1e5;return Object.is(v,-0)?0:v}function normal(a,b,c){var u=[b[0]-a[0],b[1]-a[1],b[2]-a[2]],v=[c[0]-a[0],c[1]-a[1],c[2]-a[2]],q=[u[1]*v[2]-u[2]*v[1],u[2]*v[0]-u[0]*v[2],u[0]*v[1]-u[1]*v[0]],l=Math.hypot(q[0],q[1],q[2])||1;return q.map(function(x){return n(x/l)})}function facet(a,b,c){var q=normal(a,b,c);return'facet normal '+q.join(' ')+'\n outer loop\n  vertex '+a.map(n).join(' ')+'\n  vertex '+b.map(n).join(' ')+'\n  vertex '+c.map(n).join(' ')+'\n endloop\nendfacet\n'}
 function bridge(outer,hole){var hi=0;for(var i=1;i<hole.length;i++)if(hole[i].x>hole[hi].x)hi=i;var oi=0,best=Infinity;for(i=0;i<outer.length;i++){var dx=outer[i].x-hole[hi].x,dy=outer[i].y-hole[hi].y,score=Math.hypot(dx,dy)+(dx<0?1e6:0);if(score<best){best=score;oi=i}}var out=outer.slice(0,oi+1);for(i=0;i<=hole.length;i++)out.push(hole[(hi+i)%hole.length]);out.push(outer[oi]);return out.concat(outer.slice(oi+1))}
 function cross(a,b,c){return(b.x-a.x)*(c.y-a.y)-(b.y-a.y)*(c.x-a.x)}function inside(p,a,b,c){var c1=cross(a,b,p),c2=cross(b,c,p),c3=cross(c,a,p);return c1>=-1e-9&&c2>=-1e-9&&c3>=-1e-9}
 function triangulate(outer,holes){var poly=outer.slice();(holes||[]).forEach(function(h){poly=bridge(poly,h)});var ids=poly.map(function(_,i){return i}),tris=[],guard=0;while(ids.length>3&&guard++<10000){var cut=false;for(var i=0;i<ids.length;i++){var ia=ids[(i+ids.length-1)%ids.length],ib=ids[i],ic=ids[(i+1)%ids.length],a=poly[ia],b=poly[ib],c=poly[ic];if(cross(a,b,c)<=1e-9)continue;var blocked=false;for(var j=0;j<ids.length;j++){var id=ids[j];if(id===ia||id===ib||id===ic)continue;if(inside(poly[id],a,b,c)){blocked=true;break}}if(!blocked){tris.push([a,b,c]);ids.splice(i,1);cut=true;break}}if(!cut)break}if(ids.length===3)tris.push([poly[ids[0]],poly[ids[1]],poly[ids[2]]]);return tris}
 function fromParts(parts,name){name=name||'drawforge';var out='solid '+name+'\n';(parts||[]).forEach(function(p){var o=p.outer,i;for(i=0;i<o.length;i++){var a=o[i],b=o[(i+1)%o.length];out+=facet([a.x,a.y,p.z0],[b.x,b.y,p.z0],[b.x,b.y,p.z1])+facet([a.x,a.y,p.z0],[b.x,b.y,p.z1],[a.x,a.y,p.z1])}p.holes.forEach(function(h){var bottom=h.through?p.z0:Math.max(p.z0,p.z1-h.depth),r=h.ring;for(var k=0;k<r.length;k++){var a=r[k],b=r[(k+1)%r.length];out+=facet([a.x,a.y,bottom],[b.x,b.y,p.z1],[b.x,b.y,bottom])+facet([a.x,a.y,bottom],[a.x,a.y,p.z1],[b.x,b.y,p.z1])}});var topH=p.holes.map(function(h){return h.ring}),bottomH=p.holes.filter(function(h){return h.through}).map(function(h){return h.ring});triangulate(o,topH).forEach(function(t){out+=facet([t[0].x,t[0].y,p.z1],[t[1].x,t[1].y,p.z1],[t[2].x,t[2].y,p.z1])});triangulate(o,bottomH).forEach(function(t){out+=facet([t[0].x,t[0].y,p.z0],[t[2].x,t[2].y,p.z0],[t[1].x,t[1].y,p.z0])})});return out+'endsolid '+name}
 return{normal:normal,facet:facet,triangulate:triangulate,fromParts:fromParts}
});
