"use strict";
(function(root,factory){var api=factory();if(typeof module==='object'&&module.exports)module.exports=api;root.DrawForgeSTL=api})(typeof globalThis!=='undefined'?globalThis:this,function(){
 function n(v){v=Math.round(v*1e5)/1e5;return Object.is(v,-0)?0:v}function normal(a,b,c){var u=[b[0]-a[0],b[1]-a[1],b[2]-a[2]],v=[c[0]-a[0],c[1]-a[1],c[2]-a[2]],q=[u[1]*v[2]-u[2]*v[1],u[2]*v[0]-u[0]*v[2],u[0]*v[1]-u[1]*v[0]],l=Math.hypot(q[0],q[1],q[2])||1;return q.map(function(x){return n(x/l)})}function facet(a,b,c){var q=normal(a,b,c);return'facet normal '+q.join(' ')+'\n outer loop\n  vertex '+a.map(n).join(' ')+'\n  vertex '+b.map(n).join(' ')+'\n  vertex '+c.map(n).join(' ')+'\n endloop\nendfacet\n'}
 function centroid(r){var x=0,y=0;r.forEach(function(p){x+=p.x;y+=p.y});return{x:x/r.length,y:y/r.length}}
 function rayHit(c,h,poly){var dx=h.x-c.x,dy=h.y-c.y,best=null,bestT=-Infinity;for(var i=0;i<poly.length;i++){var a=poly[i],b=poly[(i+1)%poly.length],ex=b.x-a.x,ey=b.y-a.y,den=dx*ey-dy*ex;if(Math.abs(den)<1e-9)continue;var qx=a.x-c.x,qy=a.y-c.y,t=(qx*ey-qy*ex)/den,u=(qx*dy-qy*dx)/den;if(t>=1-1e-8&&u>=-1e-8&&u<=1+1e-8&&t>bestT){bestT=t;best={x:c.x+dx*t,y:c.y+dy*t}}}return best||h}
 function simpleFan(poly){var out=[];for(var i=1;i<poly.length-1;i++)out.push([poly[0],poly[i],poly[i+1]]);return out}
 function triangulate(outer,holes){holes=holes||[];if(!holes.length)return simpleFan(outer);if(holes.length===1){var h=holes[0],c=centroid(h),rim=h.map(function(p){return rayHit(c,p,outer)}),out=[];for(var i=0;i<h.length;i++){var j=(i+1)%h.length;out.push([h[i],rim[j],rim[i]]);out.push([h[i],h[j],rim[j]])}return out}return[]}
 function fromParts(parts,name){name=name||'drawforge';var out='solid '+name+'\n';(parts||[]).forEach(function(p){var o=p.outer,i;for(i=0;i<o.length;i++){var a=o[i],b=o[(i+1)%o.length];out+=facet([a.x,a.y,p.z0],[b.x,b.y,p.z0],[b.x,b.y,p.z1])+facet([a.x,a.y,p.z0],[b.x,b.y,p.z1],[a.x,a.y,p.z1])}p.holes.forEach(function(h){var bottom=h.through?p.z0:Math.max(p.z0,p.z1-h.depth),r=h.ring;for(var k=0;k<r.length;k++){var a=r[k],b=r[(k+1)%r.length];out+=facet([a.x,a.y,bottom],[b.x,b.y,p.z1],[b.x,b.y,bottom])+facet([a.x,a.y,bottom],[a.x,a.y,p.z1],[b.x,b.y,p.z1])}});var topH=p.holes.map(function(h){return h.ring}),bottomH=p.holes.filter(function(h){return h.through}).map(function(h){return h.ring});triangulate(o,topH).forEach(function(t){out+=facet([t[0].x,t[0].y,p.z1],[t[1].x,t[1].y,p.z1],[t[2].x,t[2].y,p.z1])});triangulate(o,bottomH).forEach(function(t){out+=facet([t[0].x,t[0].y,p.z0],[t[2].x,t[2].y,p.z0],[t[1].x,t[1].y,p.z0])})});return out+'endsolid '+name}
 return{normal:normal,facet:facet,triangulate:triangulate,fromParts:fromParts}
});
